version: 2

models:
  - name: stg_applications
    columns:
      - name: application_id
        tests: [unique, not_null]
      - name: user_id
        tests: [not_null]
      - name: company
        tests: [not_null]
      - name: role
        tests: [not_null]
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ["Applied", "OA", "Interview", "Offer", "Rejected"]
      - name: source_site
        tests:
          - accepted_values:
              values: ["linkedin", "indeed", "company", "referral", "handshake", "other"]

  - name: stg_status_events
    columns:
      - name: status_event_id
        tests: [unique, not_null]
      - name: application_id
        tests: [not_null]
      - name: to_status
        tests:
          - not_null
          - accepted_values:
              values: ["Applied", "OA", "Interview", "Offer", "Rejected"]