name: "intern_tracker"
version: "1.0.0"
config-version: 2

profile: "intern_tracker"

model-paths: ["models"]
test-paths: ["tests"]

models:
  intern_tracker:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table