intern_tracker:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      dataset: analytics_intern_tracker
      location: US
      threads: 2
      keyfile_json: "{{ env_var('BQ_SERVICE_ACCOUNT_JSON') }}"